
import { type User, type Location, type Event, type Review, type CountryGroup, type Product } from './types';
import { findImage } from './placeholder-images';

export const users: User[] = [
  { id: 'user-1', name: 'Alex Johnson', email: 'alex@example.com', avatar: { imageUrl: 'https://i.pravatar.cc/150?u=user-1', imageHint: 'user avatar' }, followers: 0, following: 0 },
  { id: 'user-2', name: 'Maria Garcia', email: 'maria@example.com', avatar: { imageUrl: 'https://i.pravatar.cc/150?u=user-2', imageHint: 'user avatar' }, followers: 0, following: 0 },
  { id: 'user-3', name: 'Kenji Tanaka', email: 'kenji@example.com', avatar: { imageUrl: 'https://i.pravatar.cc/150?u=user-3', imageHint: 'user avatar' }, followers: 0, following: 0 },
  { id: 'user-4', name: 'Chloe Dubois', email: 'chloe@example.com', avatar: { imageUrl: 'https://i.pravatar.cc/150?u=user-4', imageHint: 'user avatar' }, followers: 0, following: 0 },
];

export const mainUser: User = {
  id: 'user-main',
  name: 'Sam Wilson',
  email: 'sam@example.com',
  avatar: { imageUrl: 'https://i.pravatar.cc/150?u=user-main', imageHint: 'user avatar' },
  followers: 0,
  following: 0
};

const sampleReviews: Review[] = [
    { id: 'rev-1', user: users[1], rating: 5, comment: 'Absolutely breathtaking! A must-see.' },
    { id: 'rev-2', user: users[2], rating: 4, comment: 'Great spot, but a bit crowded. Go early!' },
    { id: 'rev-3', user: users[3], rating: 5, comment: 'A life-changing experience. Highly recommend.' },
  ];

export const locations: Location[] = [
  {
    id: 'loc-1',
    caption: 'Found this magical waterfall deep in the jungle. A true hidden gem!',
    media: { url: findImage('loc-1')?.imageUrl || '', type: 'image', hint: findImage('loc-1')?.imageHint || '' },
    country: 'Costa Rica',
    city: 'La Fortuna',
    hashtags: ['#waterfall', '#jungle', '#hiddenparadise'],
    mapLink: 'https://maps.google.com',
    user: users[0],
    reviews: sampleReviews.slice(0, 2),
    likes: 150,
    howToReach: 'A 45-minute hike from the main road. The trail is marked but can be muddy after rain.',
    whatToTake: 'Sturdy hiking shoes, insect repellent, and a swimsuit if you want to take a dip!',
    entryFee: 'Free',
  },
  {
    id: 'loc-2',
    caption: 'Getting lost in the vibrant streets of this old town. Every corner is a postcard.',
    media: { url: findImage('loc-2')?.imageUrl || '', type: 'image', hint: findImage('loc-2')?.imageHint || '' },
    country: 'Portugal',
    city: 'Lisbon',
    hashtags: ['#citybreak', '#colorfulstreets', '#europe'],
    mapLink: 'https://maps.google.com',
    user: users[1],
    reviews: sampleReviews.slice(1, 3),
    likes: 320,
    howToReach: 'Best explored on foot. Take the historic Tram 28 to get to the Alfama district.',
    whatToTake: 'Comfortable walking shoes are a must. Don\'t forget your camera!',
    entryFee: 'Free',
  },
  {
    id: 'loc-3',
    caption: 'Woke up at 4 AM for this sunrise. Absolutely worth it.',
    media: { url: findImage('loc-3')?.imageUrl || '', type: 'image', hint: findImage('loc-3')?.imageHint || '' },
    country: 'Canada',
    city: 'Banff',
    hashtags: ['#mountainlife', '#sunrise', '#serenity'],
    mapLink: 'https://maps.google.com',
    user: users[2],
    reviews: [sampleReviews[0]],
    likes: 580,
    howToReach: 'The viewpoint is a 20-minute drive from the town of Banff, followed by a short, steep walk.',
    whatToTake: 'Warm layers, a hat, gloves, and a thermos of hot coffee.',
    entryFee: 'National Park Pass required',
  },
  {
    id: 'loc-4',
    caption: 'A tiny bookstore that feels like it\'s from another time. Could spend hours here.',
    media: { url: findImage('loc-4')?.imageUrl || '', type: 'image', hint: findImage('loc-4')?.imageHint || '' },
    country: 'Czech Republic',
    city: 'Prague',
    hashtags: ['#bookstore', '#cozy', '#offthebeatenpath'],
    mapLink: 'https://maps.google.com',
    user: users[3],
    reviews: [],
    likes: 95,
    howToReach: 'Tucked away in a small alley near the Old Town Square.',
    whatToTake: 'A love for books and some local currency.',
    entryFee: 'Free',
  },
  {
    id: 'loc-5',
    caption: 'The views from these cliffs are breathtaking. The ocean seems endless.',
    media: { url: findImage('loc-5')?.imageUrl || '', type: 'image', hint: findImage('loc-5')?.imageHint || '' },
    country: 'Ireland',
    city: 'Cliffs of Moher',
    hashtags: ['#coastal', '#hiking', '#dramaticview'],
    mapLink: 'https://maps.google.com',
    user: users[0],
    reviews: sampleReviews.slice(0, 1),
    likes: 840,
  },
  {
    id: 'loc-6',
    caption: 'The energy (and the food!) at this night market is incredible.',
    media: { url: findImage('loc-6')?.imageUrl || '', type: 'image', hint: findImage('loc-6')?.imageHint || '' },
    country: 'Thailand',
    city: 'Bangkok',
    hashtags: ['#nightmarket', '#streetfood', '#citylife'],
    mapLink: 'https://maps.google.com',
    user: users[1],
    reviews: [],
    likes: 410,
  },
  {
    id: 'loc-7',
    caption: 'Walking through history. It\'s humbling to see these ancient structures.',
    media: { url: findImage('loc-7')?.imageUrl || '', type: 'image', hint: findImage('loc-7')?.imageHint || '' },
    country: 'Jordan',
    city: 'Petra',
    hashtags: ['#ancientruins', '#history', '#desert'],
    mapLink: 'https://maps.google.com',
    user: users[2],
    reviews: sampleReviews.slice(0, 2),
    likes: 980,
  },
  {
    id: 'loc-8',
    caption: 'Perfect spot for a morning coffee and people-watching.',
    media: { url: findImage('loc-8')?.imageUrl || '', type: 'image', hint: findImage('loc-8')?.imageHint || '' },
    country: 'Italy',
    city: 'Rome',
    hashtags: ['#cafe', '#cobblestone', '#dolcevita'],
    mapLink: 'https://maps.google.com',
    user: users[3],
    reviews: sampleReviews.slice(1, 3),
    likes: 275,
  },
];

export const events: Event[] = [
  {
    id: 'evt-1',
    title: 'Summer Folk Music Fest',
    media: { url: findImage('evt-1')?.imageUrl || '', type: 'image', hint: findImage('evt-1')?.imageHint || '' },
    date: 'August 15, 2024',
    time: '2:00 PM - 10:00 PM',
    place: 'Green Meadows Park, Springfield',
    description: 'Enjoy a full day of live folk music from local and national artists. Food trucks, craft stalls, and good vibes all around.',
    user: users[0],
    reviews: sampleReviews.slice(0, 2),
    tickets: [
      { name: 'General Admission', price: 25 },
      { name: 'VIP Pass', price: 75 },
    ],
  },
  {
    id: 'evt-2',
    title: 'Festival of Lights',
    media: { url: findImage('evt-2')?.imageUrl || '', type: 'image', hint: findImage('evt-2')?.imageHint || '' },
    date: 'November 5, 2024',
    time: '6:00 PM onwards',
    place: 'Riverside Promenade, Newtown',
    description: 'Witness the beautiful spectacle of thousands of lanterns being released into the night sky. A magical experience for all ages.',
    user: users[1],
    reviews: [],
    tickets: [{ name: 'Free Admission', price: 0 }],
  },
  {
    id: 'evt-3',
    title: 'Harvest Farmers Market',
    media: { url: findImage('evt-3')?.imageUrl || '', type: 'image', hint: findImage('evt-3')?.imageHint || '' },
    date: 'Every Saturday in October',
    time: '9:00 AM - 1:00 PM',
    place: 'Town Square, Oldbridge',
    description: 'Stock up on the freshest local produce, baked goods, and handmade crafts. A great way to support local farmers and artisans.',
    user: users[2],
    reviews: [sampleReviews[2]],
    tickets: [],
  },
  {
    id: 'evt-4',
    title: 'Art in the Open',
    media: { url: findImage('evt-4')?.imageUrl || '', type: 'image', hint: findImage('evt-4')?.imageHint || '' },
    date: 'September 20-22, 2024',
    time: '10:00 AM - 6:00 PM',
    place: 'Seaview Sculpture Garden, Bay City',
    description: 'An open-air exhibition featuring stunning sculptures and installations from contemporary artists. Perfect for a cultural day out.',
    user: users[3],
    reviews: [],
    tickets: [{ name: 'Adult', price: 15 }, { name: 'Student', price: 10 }],
  },
];

export const countryGroups: CountryGroup[] = [
  {
    id: 'italy',
    country: 'Italy',
    flag: '🇮🇹',
    image: { imageUrl: findImage('group-italy')?.imageUrl || '', imageHint: findImage('group-italy')?.imageHint || '' },
    groups: [
      { city: 'Rome', whatsappLink: 'https://chat.whatsapp.com/group' },
      { city: 'Florence', whatsappLink: 'https://chat.whatsapp.com/group' },
      { city: 'Venice', whatsappLink: 'https://chat.whatsapp.com/group' },
    ],
  },
  {
    id: 'japan',
    country: 'Japan',
    flag: '🇯🇵',
    image: { imageUrl: findImage('group-japan')?.imageUrl || '', imageHint: findImage('group-japan')?.imageHint || '' },
    groups: [
      { city: 'Tokyo', whatsappLink: 'https://chat.whatsapp.com/group' },
      { city: 'Kyoto', whatsappLink: 'https://chat.whatsapp.com/group' },
      { city: 'Osaka', whatsappLink: 'https://chat.whatsapp.com/group' },
    ],
  },
  {
    id: 'thailand',
    country: 'Thailand',
    flag: '🇹🇭',
    image: { imageUrl: findImage('group-thailand')?.imageUrl || '', imageHint: findImage('group-thailand')?.imageHint || '' },
    groups: [
      { city: 'Bangkok', whatsappLink: 'https://chat.whatsapp.com/group' },
      { city: 'Chiang Mai', whatsappLink: 'https://chat.whatsapp.com/group' },
      { city: 'Phuket', whatsappLink: 'https://chat.whatsapp.com/group' },
    ],
  },
  {
    id: 'portugal',
    country: 'Portugal',
    flag: '🇵🇹',
    image: { imageUrl: findImage('group-portugal')?.imageUrl || '', imageHint: findImage('group-portugal')?.imageHint || '' },
    groups: [
      { city: 'Lisbon', whatsappLink: 'https://chat.whatsapp.com/group' },
      { city: 'Porto', whatsappLink: 'https://chat.whatsapp.com/group' },
    ],
  },
  {
    id: 'canada',
    country: 'Canada',
    flag: '🇨🇦',
    image: { imageUrl: findImage('group-canada')?.imageUrl || '', imageHint: findImage('group-canada')?.imageHint || '' },
    groups: [
      { city: 'Banff', whatsappLink: 'https://chat.whatsapp.com/group' },
      { city: 'Vancouver', whatsappLink: 'https://chat.whatsapp.com/group' },
    ],
  },
  {
    id: 'czech-republic',
    country: 'Czech Republic',
    flag: '🇨🇿',
    image: { imageUrl: findImage('group-czech')?.imageUrl || '', imageHint: findImage('group-czech')?.imageHint || '' },
    groups: [
      { city: 'Prague', whatsappLink: 'https://chat.whatsapp.com/group' },
    ],
  },
  {
    id: 'ireland',
    country: 'Ireland',
    flag: '🇮🇪',
    image: { imageUrl: findImage('group-ireland')?.imageUrl || '', imageHint: findImage('group-ireland')?.imageHint || '' },
    groups: [
      { city: 'Cliffs of Moher', whatsappLink: 'https://chat.whatsapp.com/group' },
      { city: 'Dublin', whatsappLink: 'https://chat.whatsapp.com/group' },
    ],
  },
   {
    id: 'jordan',
    country: 'Jordan',
    flag: '🇯🇴',
    image: { imageUrl: findImage('group-jordan')?.imageUrl || '', imageHint: findImage('group-jordan')?.imageHint || '' },
    groups: [
      { city: 'Petra', whatsappLink: 'https://chat.whatsapp.com/group' },
      { city: 'Amman', whatsappLink: 'https://chat.whatsapp.com/group' },
    ],
  },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Wanderer\'s Waterproof Backpack',
    brand: 'AquaShield',
    price: 89.99,
    rating: 4.8,
    category: 'Bags',
    description: 'A durable and stylish backpack that will keep your gear dry in any weather.',
    media: [{ url: findImage('prod-1')?.imageUrl || '', type: 'image', hint: findImage('prod-1')?.imageHint || '' }],
  },
  {
    id: 'prod-2',
    name: 'Nomad\'s Multi-Tool',
    brand: 'SwissTech',
    price: 35.50,
    rating: 4.9,
    category: 'Gadgets',
    description: 'A compact and versatile multi-tool that is a must-have for any traveler.',
    media: [{ url: findImage('prod-2')?.imageUrl || '', type: 'image', hint: findImage('prod-2')?.imageHint || '' }],
  },
  {
    id: 'prod-3',
    name: 'Traveler\'s Compression Cubes',
    brand: 'PackEasy',
    price: 25.00,
    rating: 4.6,
    category: 'Accessories',
    description: 'Maximize your luggage space with these lightweight and durable compression cubes.',
    media: [{ url: findImage('prod-3')?.imageUrl || '', type: 'image', hint: findImage('prod-3')?.imageHint || '' }],
  },
  {
    id: 'prod-4',
    name: 'Global Universal Adapter',
    brand: 'PowerLink',
    price: 22.00,
    rating: 4.7,
    category: 'Gadgets',
    description: 'Stay charged and connected wherever you go with this all-in-one universal adapter.',
    media: [{ url: findImage('prod-4')?.imageUrl || '', type: 'image', hint: findImage('prod-4')?.imageHint || '' }],
  },
  {
    id: 'prod-5',
    name: 'Merino Wool Travel Socks',
    brand: 'Hiker\'s Comfort',
    price: 18.00,
    rating: 4.9,
    category: 'Apparel',
    description: 'Keep your feet comfortable and dry on long travel days with these merino wool socks.',
    media: [{ url: findImage('prod-5')?.imageUrl || '', type: 'image', hint: findImage('prod-5')?.imageHint || '' }],
  },
  {
    id: 'prod-6',
    name: 'Collapsible Silicone Water Bottle',
    brand: 'EcoHydrate',
    price: 15.99,
    rating: 4.5,
    category: 'Accessories',
    description: 'Stay hydrated on the go with this eco-friendly and space-saving collapsible water bottle.',
    media: [{ url: findImage('prod-6')?.imageUrl || '', type: 'image', hint: findImage('prod-6')?.imageHint || '' }],
  },
    {
    id: 'prod-7',
    name: 'Quick-Dry Travel Towel',
    brand: 'DryFit',
    price: 28.00,
    rating: 4.7,
    category: 'Accessories',
    description: 'A lightweight and absorbent towel that dries quickly, perfect for any adventure.',
    media: [{ url: findImage('prod-7')?.imageUrl || '', type: 'image', hint: findImage('prod-7')?.imageHint || '' }],
  },
  {
    id: 'prod-8',
    name: 'Noise-Cancelling Travel Pillow',
    brand: 'SilentSlumber',
    price: 45.00,
    rating: 4.8,
    category: 'Comfort',
    description: 'Get some rest on the go with this comfortable and supportive noise-cancelling travel pillow.',
    media: [{ url: findImage('prod-8')?.imageUrl || '', type: 'image', hint: findImage('prod-8')?.imageHint || '' }],
  },
];
